FROM vements/substitute-server:latest AS sub

FROM --platform=$BUILDPLATFORM alpine:3.18 AS build
ARG BUILDPLATFORM


RUN apk add --no-cache \
    nodejs \
    npm \
    python3 \
    py3-pip 

WORKDIR /app
COPY --from=sub /app/subserver /app/subserver
COPY --from=sub /app/requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

COPY src /app/src
COPY test /app/test
COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json
COPY rollup.config.js /app/rollup.config.js
RUN npm install

ENV PORT=9000

ENTRYPOINT python -m subserver & \
     cd /app && \
      npm run test
