name: Build and Test

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Test Image
        run: docker build -t client-js:latest -f ./dockerfile.test .
      - name: Run Test Image
        run: docker run --rm client-js:latest

      - uses: actions/setup-node@v3
        with:
          node-version: '21.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@vements'

      - run: npm ci

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{github.workflow}}

            repository: ${{ github.repository }}

            user: ${{ github.actor }}

            commit: ${{ github.event.head_commit.message }}

            link: https://github.com/${{ github.repository }}

            link: https://github.com/${{ github.repository }}/commit/${{github.sha}}